### PR TITLE
Extend JSON API and Best Effort Node Power Cap to other architectures

### LINKED ISSUE #182: Extend JSON API support to other microarchitectures
Currently, we support JSON API only on Intel Broadwell and IBM P9, we need to support other architectures eventually.

### LINKED ISSUE #185: Extend "variorum_cap_best_effort_node_power_limit()" to support to other microarchitectures
Currently, this is only supported on Broadwell and Power9; add support to other architectures. Refer to assumptions here: [https://variorum.readthedocs.io/en/latest/VariorumAPI.html#best-effort-power-capping](https://variorum.readthedocs.io/en/latest/VariorumAPI.html#best-effort-power-capping)

### PR DESCRIPTION
**Pull request by tpatki**
Had some issue with the other pull request, git kept showing the same commit multiple times. Here's a cleaner version, the previous notes still apply. 

Update Jul 14. 6p:
- [x] JSON API works correctly on Arm Juno r2, Thompson (Haswell).
- [x] Added Best Effort Node Power Cap for other Intel microarchitectures.
- [x] Build and initial test works correctly on rhetoric (Skylake), there seems to be a minor bug with number of sockets in the -- [x] JSON object returned that needs to be fixed. Could have to do with the ongoing msr-safe development on rhetoric.

ToDo:
- [x] ARM Best Effort Power Cap ?? -- This doesn't apply as ARM doesn't support power capping -- only, frequency setting, which already exists.
- [x] Test JSON API on Rhetoric, Octomore, Folsom (and find Sandy Bridge and Kaby Lake system to test on)
- [x] Test Best Effort Node Power Cap API on all Intel microarchitectures, verify that power is set correctly on both sockets.
- [ ] Need to adjust significant digits in the values reported (converted to watts)
- [x] Fix code style errors.

Supersedes #186

### CODE REVIEW

**Comment by slabasan** [comment]
@tpatki: Can we break this into a couple PRs? I suggest one for each of the following:
- Add ARM documentation links
- Migrating dump to print in ARM's power_features.h
- Extend JSON API and best effort node power cap to other architectures

**Comment by tpatki** [comment]
Yes, I can do this. Is there a good way to handle this with git (other than creating and pushing to three separate branches)?

**Comment by slabasan** [comment]
You would have 3 separate branches, one for each feature. But, I believe the first two (ARM docs and moving ARM functions from dump to print) are already completed in this PR. If that is the case, then it should be straight-forward to create a new branch, and then use cherry-pick of the specific commit from this feature branch to your new branch. Happy to work with you on this. Since these are small, we can merge them into dev quickly and then you can rebase this branch.

**Comment by tpatki** [comment]
@slabasan 
How would you like me to break this up? I think we fixed the ARM documentation links and the dump --> print change for ARM. Is a single PR with the JSON power consumption and best effort API on other architectures sufficient for now? I can update accordingly.

**Pull request merged**
