### PR TITLE
Added Variorum logo and a note on the typeface.

### PR DESCRIPTION
**Pull request by rountree**
Let me know if you want something that will work as an icon.

### CODE REVIEW

**Comment by slabasan** [comment]
An icon would be cool! We could link it in the docs. Is this something quick and easy to do?

**Comment by rountree** [comment]
On my list.  How about the capital V in a circle, same background color?

**Comment by slabasan** [comment]
I think that's a great idea.

**Comment by rountree** [comment]
Updated the PR.

**Pull request merged**
