### PR TITLE
json output for thermal data.

### LINKED ISSUE #438: Add JSON thermal API

### PR DESCRIPTION
**Pull request by kfan326**
# Description

Added json output for thermal data: Currently implemented for Intel Skylake through Kabylake. AMD Epyc, IBM Power9, AMD GPUs, nVidia GPUs. 

Docs: https://variorum.readthedocs.io/en/pr-from-fork-434/

Commit Message:
```
json output for thermal data

-add docs
-supports AMD GPUs, nVidia GPUs, Intel CPUs, IBM Power9 CPUs
```

Fixes #438 

Open issues for:
- [x] ARM CPUs (Can test on Juno)
- [x] AMD CPUs (Need additional testing in AMD ESMI)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature/architecture support (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Build/CI update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please provide hardware architecture specs and
instructions so we can reproduce.

- [x] Tioga
- [x] Lassen
```
{
    "lassen2": {
        "timestamp": 1699313086924113,
        "socket_0": {
            "CPU": {
                "Core": {
                    "temp_celsius_core_0": 24,
                    "temp_celsius_core_1": 23,
                    "temp_celsius_core_2": 23,
                    "temp_celsius_core_3": 23,
                    "temp_celsius_core_4": 24,
                    "temp_celsius_core_5": 24,
                    "temp_celsius_core_6": 24,
                    "temp_celsius_core_7": 24,
                    "temp_celsius_core_8": 24,
                    "temp_celsius_core_9": 24,
                    "temp_celsius_core_10": 0,
                    "temp_celsius_core_11": 0,
                    "temp_celsius_core_12": 24,
                    "temp_celsius_core_13": 24,
                    "temp_celsius_core_14": 24,
                    "temp_celsius_core_15": 24,
                    "temp_celsius_core_16": 24,
                    "temp_celsius_core_17": 24,
                    "temp_celsius_core_18": 24,
                    "temp_celsius_core_19": 24,
                    "temp_celsius_core_20": 24,
                    "temp_celsius_core_21": 24,
                    "temp_celsius_core_22": 24,
                    "temp_celsius_core_23": 24
                },
                "Mem": {
                    "temp_celsius_dimm_0": 0,
                    "temp_celsius_dimm_1": 0,
                    "temp_celsius_dimm_2": 31,
                    "temp_celsius_dimm_3": 32,
                    "temp_celsius_dimm_4": 32,
                    "temp_celsius_dimm_5": 31,
                    "temp_celsius_dimm_6": 0,
                    "temp_celsius_dimm_7": 0,
                    "temp_celsius_dimm_8": 0,
                    "temp_celsius_dimm_9": 0,
                    "temp_celsius_dimm_10": 32,
                    "temp_celsius_dimm_11": 31,
                    "temp_celsius_dimm_12": 31,
                    "temp_celsius_dimm_13": 31,
                    "temp_celsius_dimm_14": 0,
                    "temp_celsius_dimm_15": 0
                }
            },
            "GPU": {
                "temp_celsius_gpu_0": 25,
                "temp_celsius_gpu_1": 25
            }
        }
    }
}
```
- [x] Octomore

# Checklist:

- [x] I have run `./scripts/check-code-format.sh` and confirm my code code follows the style guidelines of variorum
- [x] I have added comments in my code
- [x] My changes generate no new warnings (build with `-DENABLE_WARNINGS=ON`)
- [x] New and existing unit tests pass with my changes

### CODE REVIEW

**Comment by tpatki** [comment]
Hi @kfan326 : please add the documentation for this API and its structure. 
- You can follow the example from RTD here: https://variorum.readthedocs.io/en/latest/VariorumAPI.html. 
- You can create a new `.rst` page for JSON APIs, and add that under API docs section. I also plan to move the current JSON docs there once we update everything to the nested JSON format. 

I'll review and test on various platforms once we have the docs in the PR as well.

**Comment by slabasan** [comment]
@kfan326 Is this PR ready for review or do you have more changes to make? The title indicates WIP, but there is also a ready-for-review label. Happy to review once you have resolved the PR.

**Comment by kfan326** [comment]
@slabasan Yes the PR is ready for review. the Nest power/domain json api PR is ready for review as well. The frequency JSON still needs some cleaning up and should be ready soon.

**Comment by slabasan** [comment]
Closed by #461

**Pull request closed without merging**
