### PR TITLE
Changes comment in config_architecture.c to reflect current code

### LINKED ISSUE #246: Fix stale comment
Need to update comment in config_architecture.c to reflect current code

### PR DESCRIPTION
**Pull request by Jessicat-H**
Fixes #246

### CODE REVIEW

**Comment by tpatki** [comment]
@Jessicat-H
Hi Jessica, you can run `scripts/check-code-format.sh` to fix the formatting issue in the failing test, it uses `astyle` to format the files. Could you please do that and update the PR so we can merge it? It might be easier to run the script on lassen instead of power lab nodes.

Update: Looks like astyle is complaining about a trailing whitespace at the end of the line `marches forward`. @Jessicat-H if you could please delete this extra space and commit back the file, then the formatting should be all good!

**Review by tpatki — CHANGES_REQUESTED** [review]
See comment about code formatting.

**Comment by Jessicat-H** [comment]
Apologies for the delay; I forgot that my GitHub account is linked to a different email. I believe I have made the fix.

**Review by slabasan — APPROVED** [review]
LGTM thanks!

**Pull request merged**
