### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by slabasan**

### CODE REVIEW

**Comment by tpatki** [comment]
@slabasan  This is great! Thank you so much for doing this, hadn't occurred to me that we can do this :) I'll also add this to the RTD under contributions (or point to it). 
I can merge after the checks pass.

**Review by tpatki — APPROVED** [review]
Awesome!

**Comment by tpatki** [comment]
@rountree @amarathe84 Any comments here? If not, I'll go ahead and merge as this is useful for our students.

**Comment by rountree** [comment]
Line 32 is an incomplete sentence.

Line 18 has a typo (eproduce -> reproduce).

This feels a bit heavyweight, but let's run with it and see how it works in practice.

**Comment by tpatki** [comment]
@rountree I fixed the typo and removed the line about tools, I think that seemed unnecessary.

This is heavyweight but useful, I think.

**Comment by rountree** [comment]
Looks good.

**Pull request merged**
