### PR TITLE
Document that Variorum is GNU/Linux specific

### PR DESCRIPTION
**Pull request by sanmai-NL**
# Description

Document that Variorum is GNU/Linux specific.

Fixes no existing issue.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature/architecture support (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Build/CI update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please provide hardware architecture specs and
instructions so we can reproduce.

- [ ] Test A: Hardware architecture, machine name, example/test run
- [ ] Test B: Hardware architecture, machine name, example/test run
- [ ] ...

# Checklist:

- [ ] I have run `./scripts/check-code-format.sh` and confirm my code code follows the style guidelines of variorum
- [ ] I have added comments in my code
- [ ] My changes generate no new warnings (build with `-DENABLE_WARNINGS=ON`)
- [ ] New and existing unit tests pass with my changes

Thank you for taking the time to contribute to Variorum!

### CODE REVIEW

**Comment by rountree** [comment]
@sanmai-NL We're not excluding non-GNU Linuxes (e.g., Chimera).  We're also not excluding non-Linux OSes.

I could see adding a list of supported/tested kernels, kernel modules and firmware.  Would that solve this issue?

**Comment by sanmai-NL** [comment]
With GNU/Linux I refer (to the GPL-licensed) kernel. But the naming isn't my point at all. You may call it Linux.

A potential user wants to know the system requirements. Linux is required. The system's design is interesting to Variorum developers. You could have a story for both audiences, too.

**Comment by sanmai-NL** [comment]
Such a table would be helpful (for me) as long as it communicates Variorum won't work without Linux period.

**Comment by sanmai-NL** [comment]
@rountree I changed the wording and fixed the merge conflict.

**Comment by rountree** [comment]
@sanmai-NL 

How about changing 

"Variorum is an extensible vendor-neutral library for exposing power and performance monitoring and control of low-level hardware dials." 

to 

"Variorum is an extensible vendor-neutral library for Linux that exposes power and performance monitoring and control of low-level hardware dials."?

**Comment by sanmai-NL** [comment]
Doesn't ‘for Linux’ imply a constraint or design limitation, while it is a circumstantial limitation, as you suggested before?

**Comment by rountree** [comment]
Yes, it does imply a constraint or design limitation.  However, it does so in a way that won't cause our target audience to wonder what the hell we're thinking.

Does that wording solve your problem?

**Comment by sanmai-NL** [comment]
Not sure everyone will interpret it with the intended nuance, but for me the incompleteness of the docs is addressed. 🙂

**Comment by rountree** [comment]
@sanmai-NL Go ahead and modify this PR if you like, or I'll put it in myself in a couple of days.

**Comment by sanmai-NL** [comment]
@rountree Done.

**Review by slabasan — APPROVED** [review]
Thank you for contributing to Variorum!

**Pull request merged**
