### PR TITLE
Extend build for multiple platforms

### LINKED ISSUE #62: Build for node containing CPU+GPU

### PR DESCRIPTION
**Pull request by slabasan**
Resolves #62, start with IBM and Nvidia

Test platforms:
- lassen
- pascal

### CODE REVIEW

**Comment by slabasan** [comment]
```
brink2@lassen8:~/git_root_pub/variorum/build-both (build-two-archs)]$ !.
./examples/variorum-print-power-example 
_IBMPOWER Host Socket PWRSYS PWRPROC PWRMEM PWRGPU Timestamp
_IBMPOWER lassen8 0 438 114 20 67 0.000021
_IBMPOWER lassen8 1 0 108 20 64 0.000115
_GPU_POWER_USAGE Host Socket Device Power
_GPU_POWER_USAGE lassen8 0 0 35.375002
_GPU_POWER_USAGE lassen8 0 1 34.356002
_GPU_POWER_USAGE lassen8 1 2 33.858002
_GPU_POWER_USAGE lassen8 1 3 35.375002
```

**Comment by slabasan** [comment]
Extending this PR to handle control of multiple components within the node. The API can take a variable number of inputs (depending on the number of components). In this example, we build variorum for an IBM CPU and an Nvidia GPU. We specify a 10W power limit on the first architecture (happens to be IBM), and this API skips Nvidia since it hasn't been ported to this API.
```
brink2@lassen17:$ ./examples/variorum-set-node-power-limit-example 10 20
Number of registered platforms: 2

Changed node power cap to 10W.
NOTE: 
  It may take 100-500ms for power cap to propagate out of band, so please
  verify again with dump_power_limits before setting the cap again.

lassen17:/g/g19/brink2/git_root_pub/variorum/src/variorum/variorum.c:variorum_set_node_power_limit():248: _ERROR_VARIORUM_FEATURE_NOT_IMPLEMENTED: Feature not yet implemented or is not supported
```

**Comment by slabasan** [comment]
Current examples:
```
brink2@lassen35:~/git_root_pub/variorum/build-lassen-both (build-two-archs)]$ ./examples/variorum-print-power-example 
Number of registered platforms: 2
IBM -- idx0
Nvidia -- idx1
_IBMPOWER Host Socket PWRSYS_W PWRPROC_W PWRMEM_W PWRGPU_W Timestamp_sec
_IBMPOWER lassen35 0 414 78 21 100 0.000017
_IBMPOWER lassen35 1 0 80 20 83 0.000281
_NVIDIA_GPU_POWER_USAGE Host Socket DeviceID Power_W
_NVIDIA_GPU_POWER_USAGE lassen35 0 0 52.745003
_NVIDIA_GPU_POWER_USAGE lassen35 0 1 51.285002
_NVIDIA_GPU_POWER_USAGE lassen35 1 2 36.869002
_NVIDIA_GPU_POWER_USAGE lassen35 1 3 51.783002
```

```
brink2@lassen35:~/git_root_pub/variorum/build-lassen-both (build-two-archs)]$ ./examples/variorum-cap-best-effort-node-power-limit-example -l 10 -m 20 
Setting node 0 to 10W.
Setting node 1 to 20W.
Setting node to specified limits.
Number of registered platforms: 2
IBM -- idx0
Nvidia -- idx1
IBM systems may encounter a delay when setting power limits on the node.We could not verify if the power cap was set correctly.
The verification check after 100ms failed.
Please verify again with variorum_print_power_limit().
Cap node power limit failed!
```

**Comment by tpatki** [comment]
All changes from this PR have been applied and pulled into #347. Closing this as a result.

**Pull request closed without merging**
