### PR TITLE
PR from fork/455

### LINKED ISSUE #473: Update JSON APIs to have a nested format

### PR DESCRIPTION
**Pull request by slabasan**
Original PR is https://github.com/LLNL/variorum/pull/455, please refer to original PR description there. Merge original PR after all unit tests have succeeded..

The original PR needs to be merged **_after_** the JSON GPU power PR, #364 (mega merge). Tests may fail until #364 is merged because it will assume that we have the GPU API.

### CODE REVIEW

**Comment by tpatki** [comment]
Hi @kfan326 : for this PR, the nesting of GPUs seems to be missing the GPU component (the other `get_json_gpu_power` API needs to get called and added to the node power APIs on systems that have GPUs). Did you test the two APIs (json_get_node_power and json_get_gpu_power) together (we should do that in a separate PR, but checking here if you already tested this)?

**Comment by kfan326** [comment]
@tpatki I believe I tested them separately but not together. I can make a separate pr to test it combined.

**Comment by tpatki** [comment]
Hi @kfan326 : this PR also needs to update powmon, specifically the `parse_json_obj` function here: https://github.com/LLNL/variorum/blob/dev/src/powmon/common.c#L25.

**Comment by tpatki** [comment]
Closing. Merged into #490, the mega merge, and will be updated and tested on that branch.

**Pull request closed without merging**
