### PR TITLE
Report GitLab CI Status to GitHub

### PR DESCRIPTION
**Pull request by slabasan**
# Description

Want to report CI job status from gitlab to github. Status checks will show below. We will need to push pull requests directly to the upstream repo in order for these to show.

Screenshot 2023-07-27 at 10 20 50 PM

@tpatki Lassen CPU failure for `variorum_cap_best_effort_node_power_limit`. Is there a "fix" for this? Or is this a known behavior?
```
IBM systems may encounter a delay when setting power limits on the node.We could not verify if the power cap was set correctly.
The verification check after 100ms failed.
Please verify again with variorum_print_power_limit().
t_variorum_cap_best_effort_node_power_limit.cpp:15: Failure
Expected equality of these values:
  0
  variorum_cap_best_effort_node_power_limit(node_pow_limit)
    Which is: -1
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature/architecture support (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Build/CI update

# How Has This Been Tested?

- [x] lassen CPU -- known failure with variorum_cap_best_effort_node_power_limit()
- [x] quartz
- [x] catalyst
- [x] lassen GPU
- [x] lassen CPU+GPU
- [x] corona -- build on login node only, no batch runners
- [x] power lab -- no runners

# Checklist:

- [x] I have run `./scripts/check-code-format.sh` and confirm my code code follows the style guidelines of variorum
- [x] I have added comments in my code
- [x] My changes generate no new warnings (build with `-DENABLE_WARNINGS=ON`)
- [x] New and existing unit tests pass with my changes

### CODE REVIEW

**Comment by tpatki** [comment]
Add the CPU + GPU multi-arch build as well.

**Comment by tpatki** [comment]
@slabasan The 200W value specified here is too low for IBM, the minimum power cap there is 500 W (node-level with 4 GPUs). 

Power capping has a set-and-verify to address the 100ms delay, so it will fail if the verification check (new power cap != current power cap) fails. See here: https://github.com/LLNL/variorum/blob/6ea264438e4830897e393fb70abe3ba0dd1d1968/src/variorum/IBM/Power9.c#L213C3-L221C6.

Let me think about how to address this for the scenario where the power cap specified is too low for IBM. We can simply add a fix that checks if the input power cap is lower than 500, and then print an error message and return a `0` (success). 

https://github.com/LLNL/variorum/blob/dev/src/tests/variorum/t_variorum_cap_best_effort_node_power_limit.cpp#L14 .

Let me build and test this and report back shortly.

**Comment by slabasan** [comment]
Sorry @tpatki, my comment above regarding the lassen test failure were supposed to go to #435. This has been resolved through an environment variable, and the lassen test is passing now.

**Review by tpatki — DISMISSED** [review]
LGTM @slabasan (now that catalyst is removed). Ok with merging.

**Pull request merged**
